# verified on https://config.travis-ci.com/explore
language: rust
os: linux
dist: xenial
jobs:
  fast_finish: true
  include:
    - rust: stable
before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install -y nodejs
  - sudo pip install --upgrade pip
  - pip install pre-commit --user
  - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
  - rustup component add clippy --toolchain stable-x86_64-unknown-linux-gnu
script:
  - pre-commit run -a
  - cargo update
  - cargo check --all --no-default-features
  - cargo test --all-features --all -- --nocapture
  - cd riker-macros; cargo test --no-default-features -- --nocapture; cd ..
